### ISSUE TITLE
Phone number not filtered before sending to phone.

### ISSUE THREAD

**Issue by 0x566164696D** [tap-chris/cisco-dialer#3]
Hi. I very happy to find this plugin, its exactly what I looking for. Thank you!
But I have a problem.
Many sites have phone numbers like this 8 800 333-11-222 or +7 495 222 11 11
or (495) 222-11-11 or 495 222-1-111. There are more variants.
Current version of cisco-dialer don't filter what I select on web page.
If string contains space, plugin send to phone part of string and phone get only part of the number.
If string contains other characters “().+-, etc” its sends to phone too.

Can you write function, what filter input and normalized it before send to phone?

**Comment by tap-chris** [comment]
You're welcome!
What version are you using currently?
What is your country?

The plugin actually normalizes the numbers before sending them to the phone.
If I dial, for example `(495) 222-11-11`,  it translates it to `04952221111` (with country set to Germany).
There is only one case where it doesn't normalize the number and that's when you dial from contacts or context menu and the phone number is reported as invalid for your region. This is due to support for custom strings and internal numbers.

This I have to validate first and then I'll dig into the code.
Greetings, Chris

**Comment by 0x566164696D** [comment]
Hi, Chris.
Version 1.2.2 beta 
Country Russia and i try Germany too.

Now I set country to Germany and try to dial “(495) 222-11-11”  from this page via context menu.
Phone get only “(495)”

When I try to dial +7 495 287-42-41 (for example) phone get nothing.

**Comment by tap-chris** [comment]
Thank you for your help!

I did set mine to Russian and tried both numbers.
Via Click to Dial it actually works correctly but via the context menu it does indeed do something wrong.
I'll dig into it and will let you know asap.

Greetings,
Chris

**Comment by tap-chris** [comment]
A new beta version including the bugfix is on it's way.
It usually takes up to 60 minutes until it's live in the chrome webstore.
Let me know after you have the update if it's working for you now.

Greetings,
Chris

**Comment by 0x566164696D** [comment]
I try ~10 different sites with different phone numbers.
It works great!
Chris, thank you for this plugin.
I, my coworkers and friends will be a little happier ;)
Tomorrow I try other numbers. If I find a problem I tell you.

Many thanks,
Vadim

**Comment by tap-chris** [comment]
I'm glad to hear that!
Thank you very much and you're welcome.

Greetings,
Chris
